name: Terraform CI/CD

on:
  push:
    branches: [main]
    paths: ['terraform/**']
  workflow_dispatch:
    inputs:
      tf_action:
        description: 'Terraform action'
        required: true
        default: 'plan'
        type: choice
        options: [plan, apply, destroy]

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure GCP credentials
        run: |
          echo '${{ secrets.TF_WITH_GCP_KEY }}' > gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$PWD/gcp-key.json"
        shell: bash

      - name: Terraform Init
        run: terraform init -backend-config="credentials=gcp-key.json"

      - name: Terraform Plan
        if: ${{ github.event.inputs.tf_action == 'plan' || github.event_name == 'push' }}
        run: terraform plan -input=false
        env:
          TF_VAR_db_password: ${{ secrets.POSTGRES_PASSWORD }}
          GOOGLE_APPLICATION_CREDENTIALS: $PWD/gcp-key.json

      - name: Terraform Apply
        if: ${{ github.event.inputs.tf_action == 'apply' }}
        run: terraform apply -auto-approve
        env:
          TF_VAR_db_password: ${{ secrets.POSTGRES_PASSWORD }}
          GOOGLE_APPLICATION_CREDENTIALS: $PWD/gcp-key.json

      - name: Terraform Destroy
        if: ${{ github.event.inputs.tf_action == 'destroy' }}
        run: terraform destroy -auto-approve
        env:
          TF_VAR_db_password: ${{ secrets.POSTGRES_PASSWORD }}
          GOOGLE_APPLICATION_CREDENTIALS: $PWD/gcp-key.json
